### ISSUE TITLE
Cant Craft Fabricator Controller

### ISSUE THREAD

**Issue by GirlGamer42069** [Trnrr/infamy-reloaded-issue-tracker#14]
cant craft fabricator controller cause u cant make cybernetic parts and u need them to make the fabricator housing

**Comment by Trnrr** [comment]
Not really a bug, an oops on my part. The only way to obtain cybernetic parts are from Techguns mobs(which were all disabled on 2.0 update). I will add some back to incontrol and have it fixed before next update. Thanks for reporting!
